print("Nombre: Cesar Daniel Martinez Montejo")
print("Carnet: 15313-24")
print("Universidad Rafael Landivar")
print("Facultad de Ingeniaria")
print("RFRJ+6RC, 14 Avenida, Quetzaltenango")
print("CAMPUS SAN ALBERTO HURTADO, S. J. DE QUETZALTENANGO")
